#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
#python -u inspect_integration.py "$@" --input /data/sns_all_int_260513/scvi_large_Whole_Ganglia_20260513_hvgs/whole_ganglia_scvi_int_20260318.h5ad --output-dir ../results/rounds/round_01/
python -u ./integrate_sns_scvi.py "$@" --config ./pipeline_scvi.yml